name: PR checks
run-name: ${{ github.actor }} wants to add yaml data
on: push
jobs:
  Security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Echo test
        run: |
          echo ${{ github.repository_owner }} ${{ github.actor }}
          echo ${{ github.repository_owner_id }} ${{ github.actor_id }}
      
      - name: Github repo owner check
        if: ${{ github.repository_owner_id != github.actor_id }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Actor is not an owner')
