name: Push test
run-name: ${{ github.actor }} is testing out the push test
on: [push]
jobs:
  process-pushed-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      
      - name: Checkout receiver repo
        uses: actions/checkout@v4
        with:
          repository: ThomasNagel/PushReceiver
          token: ${{ secrets.PUSHRECEIVER_TOKEN }}
          path: PushReceiver

      - name: Push to receiver repo
        run: echo test
