name: Push test
run-name: ${{ github.actor }} is testing out the push test
on:
  push:
    paths:
      - '**.yml'
jobs:
  check-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Echo test
        run: echo "test"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Echo test
        run: echo "test"
