name: Push test
run-name: ${{ github.actor }} is testing out the push test
on:
  push:

jobs:
  check-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Echo test
        run: |
          echo ${{ github.repository_owner }} ${{ github.actor }}
          echo ${{ github.repository_owner_id }} ${{ github.actor_id }}
      
      - name: Github repo owner check
        if: ${{ github.repository_owner_id }} != ${{ github.actor_id }}
        uses: actions/github-script@v3
        with:
          script: |
              echo ${{ github.repository_owner_id }} ${{ github.actor_id }}
              core.setFailed('Actor is not an owner')

  test:
    needs: check-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Echo test
        run: echo "test"
