name: Push test
run-name: ${{ github.actor }} is testing out the push test
on:
  push:
    paths:
      - '**.yml'
jobs:
  build-db-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout receiver repo
        uses: actions/checkout@v4
        with:
          repository: ThomasNagel/PushReceiver
          token: ${{ secrets.PUSHRECEIVER_TOKEN }}

      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: yaml-files
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install yalm-to-sqlite dependency
        run: pip3 install -r yaml-files/requirements.txt

      - name: create Database
        run: bash yaml-files/createDB.sh yaml-files metadata.db

      - name: config git settings
        run: |
          git config --global user.name 'push repo'
          git config --global user.email 'not@important.com'
      
      - name: test2
        run: |
          ls
          cat metadata.db

      - name:
        run: |
          git add metadata.db
          git commit -m 'DATABASE'

      - name: push
        run: git push origin main
