name: Push test
run-name: ${{ github.actor }} is testing out the push test
on:
  push:
    paths:
      - '**.yml'
jobs:
  process-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      
      - name: Build Database
        run: bash createDB.sh

  push-to-remote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout receiver repo
        uses: actions/checkout@v4
        with:
          repository: ThomasNagel/PushReceiver
          token: ${{ secrets.PUSHRECEIVER_TOKEN }}

      - name: config git settings
        run: |
          git config --global user.name 'push repo'
          git config --global user.email 'not@important.com'
      - name: pull    
        run: git pull
      - name: push
        run: git push origin main
