name: Push test
run-name: ${{ github.actor }} is testing out the push test
on: [push]
jobs:
  process-pushed-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      
      - name: Checkout receiver repo
        uses: actions/checkout@v4
        with:
          repository: ThomasNagel/PushReceiver
          token: ${{ secrets.PUSHRECEIVER_TOKEN }}
          path: pushreceiver

      - name: config git settings
        run: |
          git config --global user.name 'push repo'
          git config --global user.email 'not@important.com'
          touch test.txt
          git add test.txt
          git commit -m 'test'
          git remote set-url origin pushreceiver
      - name: pull    
        run: git pull
      - name: push
        run: git push origin main
